<?php
/**
 * @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$elementNameEscaped = $block->escapeHtmlAttr($block->getElement()->getName()) . '[images]';
$formNameEscaped = $block->escapeHtmlAttr($block->getFormName());

/** @var \Magento\Framework\Json\Helper\Data $jsonHelper */
$jsonHelper = $block->getData('jsonHelper');
?>

<div id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
     class="gallery"
     data-mage-init='{"openVideoModal":{}}'
     data-parent-component="<?= $block->escapeHtml($block->getData('config/parentComponent')) ?>"
     data-images="<?= $block->escapeHtmlAttr($block->getImagesJson()) ?>"
     data-types='<?= /* @noEscape */ $jsonHelper->jsonEncode($block->getImageTypes()) ?>'>
    <?php if (!$block->getElement()->getReadonly()): ?>
        <div class="image image-placeholder">
            <?= $block->getUploaderHtml(); ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?= $block->escapeHtml(__('Browse to find or drag image here')); ?>
                </p>
            </div>
        </div>
        <?= $block->getChildHtml('additional_buttons') ?>
    <?php endif; ?>
    <?php foreach ($block->getImageTypes() as $typeData): ?>
        <input name="<?= $block->escapeHtmlAttr($typeData['name']) ?>"
               data-form-part="<?= $formNameEscaped ?>"
               class="image-<?= $block->escapeHtmlAttr($typeData['code']) ?>"
               type="hidden"
               value="<?= $block->escapeHtmlAttr($typeData['value']) ?>"/>
    <?php endforeach; ?>
</div>
<script id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>-template" data-template="image" type="text/x-magento-template">
    <div class="image item <% if (data.disabled == 1) { %>hidden-for-front<% } %>
            <% if (data.video_url) { %>video-item<% } %>"
         data-role="image">
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][position]"
               value="<%- data.position %>"
               data-form-part="<?= $formNameEscaped ?>"
               class="position"/>
        <% if (data.media_type !== 'external-video') {%>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][media_type]"
               data-form-part="<?= $formNameEscaped ?>"
               value="image"/>
        <% } else { %>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][media_type]"
               value="<%- data.media_type %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <% } %>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][video_provider]"
               value="<%- data.video_provider %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][file]"
               value="<%- data.file %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][value_id]"
               value="<%- data.value_id %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][label]"
               value="<%- data.label %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][disabled]"
               value="<%- data.disabled %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][removed]"
               value="" class="is-removed"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][video_url]"
               value="<%- data.video_url %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][video_title]"
               value="<%- data.video_title %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][video_description]"
               value="<%- data.video_description %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][video_metadata]"
               value="<%- data.video_metadata %>"
               data-form-part="<?= $formNameEscaped ?>"/>
        <input type="hidden"
               name="<?= $elementNameEscaped ?>[<%- data.file_id %>][role]"
               value="<%- data.video_description %>"
               data-form-part="<?= $formNameEscaped ?>"/>

        <div class="product-image-wrapper">
            <img data-role="image-element" class="product-image" src="<%- data.file %>"/>
        </div>
    </div>
</script>
